
[functions.init-payment]
enabled = true
verify_jwt = true
import_map = "./functions/init-payment/deno.json"
entrypoint = "./functions/init-payment/index.ts"

[functions.handleAgentWithdrawal]
enabled = true
verify_jwt = true
import_map = "./functions/handleAgentWithdrawal/deno.json"
entrypoint = "./functions/handleAgentWithdrawal/index.ts"

[functions.registerPaystackRecipient]
enabled = true
verify_jwt = false
import_map = "./functions/registerPaystackRecipient/deno.json"
entrypoint = "./functions/registerPaystackRecipient/index.ts"

[functions.init-agent-wallet]
enabled = true
verify_jwt = true
import_map = "./functions/init-agent-wallet/deno.json"
entrypoint = "./functions/init-agent-wallet/index.ts"

[functions.verify-bank-account]
enabled = true
verify_jwt = true
import_map = "./functions/verify-bank-account/deno.json"
entrypoint = "./functions/verify-bank-account/index.ts"

[functions.verify-wallet-payment]
enabled = true
verify_jwt = true
import_map = "./functions/verify-wallet-payment/deno.json"
entrypoint = "./functions/verify-wallet-payment/index.ts"
